version: 2.1

jobs:
  build-and-run-npm-project:
    docker:
      - image: cimg/node:20.11

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install NPM Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Start NPM Project
          command: npm start

workflows:
  version: 2
  npm-build-and-start:
    jobs:
      - build-and-run-npm-project:
          filters:
            branches:
              only: main
